/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWizardRouteImport } from './routes/_authenticated/wizard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNewBoxRouteImport } from './routes/_authenticated/new-box'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDoneRouteImport } from './routes/_authenticated/done'
import { Route as AuthenticatedBriefingRouteImport } from './routes/_authenticated/briefing'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated/history.index'
import { Route as AuthenticatedHistoryHandlingIdRouteImport } from './routes/_authenticated/history.$handlingId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWizardRoute = AuthenticatedWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewBoxRoute = AuthenticatedNewBoxRouteImport.update({
  id: '/new-box',
  path: '/new-box',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoneRoute = AuthenticatedDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBriefingRoute = AuthenticatedBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHistoryRoute,
  } as any)
const AuthenticatedHistoryHandlingIdRoute =
  AuthenticatedHistoryHandlingIdRouteImport.update({
    id: '/$handlingId',
    path: '/$handlingId',
    getParentRoute: () => AuthenticatedHistoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/done': typeof AuthenticatedDoneRoute
  '/history': typeof AuthenticatedHistoryRouteWithChildren
  '/new-box': typeof AuthenticatedNewBoxRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wizard': typeof AuthenticatedWizardRoute
  '/history/$handlingId': typeof AuthenticatedHistoryHandlingIdRoute
  '/history/': typeof AuthenticatedHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/done': typeof AuthenticatedDoneRoute
  '/new-box': typeof AuthenticatedNewBoxRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wizard': typeof AuthenticatedWizardRoute
  '/': typeof AuthenticatedIndexRoute
  '/history/$handlingId': typeof AuthenticatedHistoryHandlingIdRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/briefing': typeof AuthenticatedBriefingRoute
  '/_authenticated/done': typeof AuthenticatedDoneRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRouteWithChildren
  '/_authenticated/new-box': typeof AuthenticatedNewBoxRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/wizard': typeof AuthenticatedWizardRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/history/$handlingId': typeof AuthenticatedHistoryHandlingIdRoute
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/briefing'
    | '/done'
    | '/history'
    | '/new-box'
    | '/profile'
    | '/wizard'
    | '/history/$handlingId'
    | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/briefing'
    | '/done'
    | '/new-box'
    | '/profile'
    | '/wizard'
    | '/'
    | '/history/$handlingId'
    | '/history'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/briefing'
    | '/_authenticated/done'
    | '/_authenticated/history'
    | '/_authenticated/new-box'
    | '/_authenticated/profile'
    | '/_authenticated/wizard'
    | '/_authenticated/'
    | '/_authenticated/history/$handlingId'
    | '/_authenticated/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wizard': {
      id: '/_authenticated/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof AuthenticatedWizardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-box': {
      id: '/_authenticated/new-box'
      path: '/new-box'
      fullPath: '/new-box'
      preLoaderRoute: typeof AuthenticatedNewBoxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/done': {
      id: '/_authenticated/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof AuthenticatedDoneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/briefing': {
      id: '/_authenticated/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof AuthenticatedBriefingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedHistoryRoute
    }
    '/_authenticated/history/$handlingId': {
      id: '/_authenticated/history/$handlingId'
      path: '/$handlingId'
      fullPath: '/history/$handlingId'
      preLoaderRoute: typeof AuthenticatedHistoryHandlingIdRouteImport
      parentRoute: typeof AuthenticatedHistoryRoute
    }
  }
}

interface AuthenticatedHistoryRouteChildren {
  AuthenticatedHistoryHandlingIdRoute: typeof AuthenticatedHistoryHandlingIdRoute
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
}

const AuthenticatedHistoryRouteChildren: AuthenticatedHistoryRouteChildren = {
  AuthenticatedHistoryHandlingIdRoute: AuthenticatedHistoryHandlingIdRoute,
  AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
}

const AuthenticatedHistoryRouteWithChildren =
  AuthenticatedHistoryRoute._addFileChildren(AuthenticatedHistoryRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBriefingRoute: typeof AuthenticatedBriefingRoute
  AuthenticatedDoneRoute: typeof AuthenticatedDoneRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRouteWithChildren
  AuthenticatedNewBoxRoute: typeof AuthenticatedNewBoxRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWizardRoute: typeof AuthenticatedWizardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBriefingRoute: AuthenticatedBriefingRoute,
  AuthenticatedDoneRoute: AuthenticatedDoneRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRouteWithChildren,
  AuthenticatedNewBoxRoute: AuthenticatedNewBoxRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWizardRoute: AuthenticatedWizardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
